params:
  seed: 42
  algo:
    name: a2c_continuous
  
  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default 
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      d2rl: False 
      initializer:
        name: default
      regularizer:
        name: None
  
  load_checkpoint: False
  load_path: ''

  config:
    name: UR5eVSGTask # ${resolve_default:UR5VSGTask,${....experiment}}
    env_name: rlgpu
    multi_gpu: False
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: 8192 # 1024*8
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.995
    tau: 0.95
    learning_rate: 1e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 150 
    max_epochs: 3000
    save_best_after: 25
    save_frequency: 25
    print_stats: True
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True 
    e_clip: 0.2
    horizon_length: 128
    minibatch_size: 16384
    mini_epochs: 8
    critic_coef: 2
    clip_value: True 
    seq_len: 32
    bounds_loss_coef: 0.0001
